In [75]:
from igraph import *
import numpy as np

In [76]:
class Aluno(object):
    def __init__(self, codigo, area):
        self.codigo_aluno = codigo
        self.area_pesquisa = area
    
    def __repr__(self):
        to_string = "Código Aluno: " + str(self.codigo_aluno)
        to_string += ", Área de Pesquisa: " + str(self.area_pesquisa)
        return to_string
        

In [80]:
file = open('Aluno_Area_Pesquisa.txt', 'r').read()
lines = file.split('\n')
alunos = []
for line in lines:
    line = line.split(' ')
    codigo_aluno = int(line[0])
    area_pesquisa = int(line[1])
    a = Aluno(codigo_aluno, area_pesquisa)
    alunos.append(a)
alunos

[Código Aluno: 1, Área de Pesquisa: 1,
 Código Aluno: 2, Área de Pesquisa: 1,
 Código Aluno: 3, Área de Pesquisa: 3,
 Código Aluno: 4, Área de Pesquisa: 2,
 Código Aluno: 5, Área de Pesquisa: 2,
 Código Aluno: 6, Área de Pesquisa: 3,
 Código Aluno: 7, Área de Pesquisa: 1,
 Código Aluno: 8, Área de Pesquisa: 1,
 Código Aluno: 9, Área de Pesquisa: 3,
 Código Aluno: 10, Área de Pesquisa: 2,
 Código Aluno: 11, Área de Pesquisa: 2]

In [70]:
def completa_matriz(matriz_triangulo):
    matriz_triangulo.sort(key=len, reverse=True)
    lado = len(matriz_triangulo)
    matriz = np.zeros((lado, lado))
    for i in range(lado):
        for j in range(len(matriz_triangulo[i])):
            matriz[i][i+j] = matriz_triangulo[i][j]
            matriz[i+j][i] = matriz_triangulo[i][j]
    return matriz
    

In [71]:
file = open('Matriz_Dissimilaridade.txt', 'r').read()
lines = file.split('\n')
matriz_triangulo = []
for l in lines:
    l = l.split(' ')
    l = list(filter(None, l))
    matriz_triangulo.append(l)
matriz = completa_matriz(matriz_triangulo)
matriz

[[ 0. 80. 10.]
 [80.  0. 80.]
 [10. 80.  0.]]


In [89]:
def dist_aluno(aluno1, aluno2):
    area1 = aluno1.area_pesquisa
    area2 = aluno2.area_pesquisa
    return matriz[area1-1][area2-1]
    

In [90]:
dist_aluno(alunos[0],alunos[2])

10.0

In [98]:
class Grafo(object):
    def __init__(self, vertices, arestas):
        self.vertices = vertices
        self.arestas = arestas
    
    

In [91]:
def dist_grafo(grafo1, grafo2):
    sum_dist = 0
    for aluno1 in grafo1.vertices:
        for aluno2 in grafo2.vertices:
            sum_dist += dist_aluno(aluno1, aluno2)
    n = len(grafo1.vertices)
    m = len(grafo2.vertices)
    media_dist = sum_dist/(n*m)
    return media_dist
        

In [102]:
alunos1 = alunos[:5]
alunos2 = alunos[5:]
#alunos1, alunos2
grafo1 = Grafo(alunos1,[])
grafo2 = Grafo(alunos2,[])
dist_grafo(grafo1, grafo2)

39.333333333333336